### ISSUE TITLE
Add an option to comment on Passing/Failing a test

### ISSUE THREAD

**Issue by kra3** [tests-assistant/tests-assistant#20]

**Comment by ghost** [comment]
finished in 2e65befae970cfdf0adf1cb8a35344636dca3fcb

**Comment by kra3** [comment]
I can't see that commit. Do you pushed it @amirouche ?

**Comment by ghost** [comment]
https://github.com/tests-assistant/tests-assistant/commit/2e65befae970cfdf0adf1cb8a35344636dca3fcb
