### ISSUE TITLE
Reworking forms for bootstrap 3 ?

### ISSUE THREAD

**Issue by ghost** [tests-assistant/tests-assistant#24]
Right now using bootstrap makes it difficult to reuse Django magic form generation and errors reporting see the new edit test page. We can use the same trick everywhere.

**Comment by kra3** [comment]
I was wondering the other day, why we are not make use of django forms in templates.
So, great initiative.

**Comment by ghost** [comment]
Right now there is no solution to use django form generation with bootstrap 3. Maybe a module for django crispy forms is needed but I'd like to keep the dependencies to a minimum, what do you think ?

**Comment by ghost** [comment]
https://github.com/maraujop/django-crispy-forms/issues/209

**Comment by kra3** [comment]
I
​f you ask me, I never​ use a project like crispy-forms or anything like
that.

I just unpack forms object directly on the view the way I want.
And I feel I have more comfort and power by doing so.

**Comment by ghost** [comment]
That is my question whether 

1) to continue unpack forms and do things manually
2) to something smart with crispy forms

I also prefer 1)

**Comment by kra3** [comment]
Great. Let's do it manually. It's not much work anyway.
