### ISSUE TITLE
Namespaced tags

### ISSUE THREAD

**Issue by ghost** [tests-assistant/tests-assistant#25]
using only version to categorize runs is broken sometimes we need more than that, for instance:
- who does the run
- which platform
- which version
- which sprint

basicaly we need more liberty to and I think it's needed to be able to tag runs. But using taggit as-is, is not efficient. https://crate.io/packages/django-taggit-machinetags/?version=latest seems to fill the need.

**Comment by ghost** [comment]
So there will be two namespaces `test` and `run` each of which with it's own set of tags.

**Comment by kra3** [comment]
Sorry. I didn't get it even though I'm riding with Absolute :wine_glass: 

i can understand tags for tests; ie,, to get a set of tags to add to a specific run and all...
But, what's the purpose for name-spacing runs? runs for stand-by/iml and stuff like that???

If it's so, how doe's it solves the points that you described above?

**Comment by ghost** [comment]
we can use tags in runs so that we now for each run what was its purpose: `gen3000`, `S17 (1)` etc...

**Comment by ghost** [comment]
cf. #27
