### ISSUE TITLE
Move to an organization

### ISSUE THREAD

**Issue by ghost** [tests-assistant/tests-assistant#26]
So do we move to an organisation ? I find it more neutral. it's more fair.

With the this logo

![test-assistant](https://f.cloud.github.com/assets/615598/1141521/18d89792-1cb6-11e3-84ec-52bbbb7cf83f.png)

Maybe we should think more about the logo, I will do other versions that will look less socialist

**Comment by ghost** [comment]
![test-assistant3](https://f.cloud.github.com/assets/615598/1141614/e99d6b0e-1cb7-11e3-87ec-816ef99659b7.png)

**Comment by ghost** [comment]
![test-assistant2](https://f.cloud.github.com/assets/615598/1141615/e9bb19a6-1cb7-11e3-8d88-c211849de811.png)

**Comment by ghost** [comment]
![test-assistant3](https://f.cloud.github.com/assets/615598/1141624/195d74f6-1cb8-11e3-86fd-1295d287cea1.png)

**Comment by ghost** [comment]
I like the last one better

**Comment by kra3** [comment]
Let's do it. 

Like a Viking :tada: 

So, What are you waiting for?

**Comment by kra3** [comment]
btw. I read a blog post few years back regarding the leaves in the logo and the font used.
leaves make the logo looks like official, if the font is correct (ie., not Comic Sans)

**Comment by ghost** [comment]
done!

**Comment by kra3** [comment]
:+1:mais, ajouter moi aussi.
