### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by kra3** [tests-assistant/tests-assistant#30]
@amirouche please consider setting up a test project following readme

ie., 
- create a new django project
- install django-tests-assistant (this project) 
- follow the readme 

I feel sleepy now, and haven't tested it that way. but theoretically it should work.
I'll do it tomorrow if you haven't done so already

**Comment by ghost** [comment]
It doesn't work the settings are not working properly see the example project https://github.com/tests-assistant/tests-assistant/commit/aa72443d7a8e95b7a386e5e8b6687433cbc0d35d

Also whoosh index should be in a dedicated folder we cannot assume that a test assistant package will be used for by only one project.

NB: I also commited my fix on tag cloud select :/

**Comment by kra3** [comment]
I wonder how you managed to test it, as packaged pypi version won't install (0.1.1) due to missing entry in Manifest.in
I've fixed the package anyways (0.1.2)

About, app set -up I'll update after finishing my experiment

**Comment by kra3** [comment]
package is good to install now (you probably still need setuptools or distribute installed)

sample django project integration is done and created a separate repo for  that https://github.com/tests-assistant/example-tests-assistant-integration
